services:
  - type: web
    name: docverify-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: JWT_EXPIRE
        value: 24h
      - key: BASE_URL
        sync: false # Will be set manually
      - key: CORS_ORIGIN
        sync: false # Will be set manually
      # Sensitive variables - don't include in yaml
      # - MONGODB_URI
      # - JWT_SECRET
      # - ENCRYPTION_KEY
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
